#                        Sheth L.U.J And Sir M.V college
Kunal Joshi | T086
Practical No. 3A

Aim: Feature Scaling and Dummification


*   Apply feature-scaling techniques like standardization and normalization to numerical features
*  Perform feature dummification to convert categorical variables into numerical representations.







#Part 1: Handling Numerical Data (Setup)

In [35]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.impute import SimpleImputer
from sklearn.cluster import KMeans

# Sample Data from Heart Disease dataset
data = pd.read_csv("heart.csv")

df = pd.DataFrame(data)
print("Original Data:\n", df.head())

Original Data:
    age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0  


#2: Rescaling a Feature (MinMax Scaling)

In [36]:
feature = df[['age']].values

minmax_scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))
scaled_feature = minmax_scaler.fit_transform(feature)

print("\nScaled Age (0-1):\n", scaled_feature)


Scaled Age (0-1):
 [[0.47916667]
 [0.5       ]
 [0.85416667]
 ...
 [0.375     ]
 [0.4375    ]
 [0.52083333]]


#3: Standardizing a Feature (Z-Score & Robust)

In [37]:
# A. Standard Scaler (Z-Score) on 'trestbps'
feature_bps = df[['trestbps']].values
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(feature_bps)

print("\nStandardized trestbps:\n", standardized)
print("Mean:", round(standardized.mean()))
print("Std Dev:", standardized.std())

# B. Robust Scaler on 'chol' (Good for outliers)
feature_chol = df[['chol']].values
robust_scaler = preprocessing.RobustScaler()
robust_chol = robust_scaler.fit_transform(feature_chol)

print("\nRobust Scaled Chol:\n", robust_chol)


Standardized trestbps:
 [[-0.37763552]
 [ 0.4791073 ]
 [ 0.76468824]
 ...
 [-1.23437834]
 [-1.23437834]
 [-0.66321646]]
Mean: 0
Std Dev: 1.0

Robust Scaled Chol:
 [[-0.4375  ]
 [-0.578125]
 [-1.03125 ]
 ...
 [ 0.546875]
 [ 0.21875 ]
 [-0.8125  ]]


#4: Normalizing Observations

In [38]:
# Target: Combining 'age' and 'thalach' into a vector
features_vector = df[['age', 'thalach']].values.astype(float)

# L2 Normalization (Euclidean norm)
normalizer_l2 = preprocessing.Normalizer(norm="l2")
print("\nL2 Normalization:\n", normalizer_l2.transform(features_vector))

# Max Normalization
normalizer_max = preprocessing.Normalizer(norm="max")
print("\nMax Normalization:\n", normalizer_max.transform(features_vector))


L2 Normalization:
 [[0.29568373 0.95528589]
 [0.32354386 0.94621317]
 [0.48860337 0.87250602]
 ...
 [0.37003286 0.92901867]
 [0.2999826  0.95394467]
 [0.43117294 0.9022693 ]]

Max Normalization:
 [[0.30952381 1.        ]
 [0.34193548 1.        ]
 [0.56       1.        ]
 ...
 [0.39830508 1.        ]
 [0.31446541 1.        ]
 [0.47787611 1.        ]]


#5: Grouping Observations Using Clustering

In [39]:
# Grouping patients based on 'age' and 'chol'
features_cluster = df[['age', 'chol']]

# Create 2 clusters
clusterer = KMeans(n_clusters=2, random_state=0)
clusterer.fit(features_cluster)

# Assign the group to the dataframe
df['group'] = clusterer.predict(features_cluster)

print("\nData with Cluster Groups:\n", df[['age', 'chol', 'group']])


Data with Cluster Groups:
       age  chol  group
0      52   212      0
1      53   203      0
2      70   174      0
3      61   203      0
4      62   294      1
...   ...   ...    ...
1020   59   221      0
1021   60   258      1
1022   47   275      1
1023   50   254      0
1024   54   188      0

[1025 rows x 3 columns]


#6: Handling Missing Numerical Values

In [40]:
# Setup: Creating a numpy array with NaNs based on 'oldpeak' and 'chol'
features_missing = np.array([
    [1.0, 212],
    [3.1, 203],
    [np.nan, 174], # Missing oldpeak
    [0.0, np.nan], # Missing chol
    [1.9, 294]
])

print("\nOriginal Features with NaN:\n", features_missing)

# A. Drop Observations with NaN
clean_features = features_missing[~np.isnan(features_missing).any(axis=1)]
print("\nDropped Rows with NaN:\n", clean_features)

# B. Impute with Mean
mean_imputer = SimpleImputer(strategy="mean")
features_mean = mean_imputer.fit_transform(features_missing)
print("\nImputed with Mean:\n", features_mean)

# C. Impute with Median
median_imputer = SimpleImputer(strategy="median")
features_median = median_imputer.fit_transform(features_missing)
print("\nImputed with Median:\n", features_median)


Original Features with NaN:
 [[  1.  212. ]
 [  3.1 203. ]
 [  nan 174. ]
 [  0.    nan]
 [  1.9 294. ]]

Dropped Rows with NaN:
 [[  1.  212. ]
 [  3.1 203. ]
 [  1.9 294. ]]

Imputed with Mean:
 [[  1.   212.  ]
 [  3.1  203.  ]
 [  1.5  174.  ]
 [  0.   220.75]
 [  1.9  294.  ]]

Imputed with Median:
 [[  1.   212.  ]
 [  3.1  203.  ]
 [  1.45 174.  ]
 [  0.   207.5 ]
 [  1.9  294.  ]]
